name: Bash Trace
on:
  workflow_dispatch:
jobs:
  log-trace:
    runs-on: ubuntu-latest
    steps:
      - name: Debug commands
        run: |
          set -x
          date
          hostname
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
