name: Dump workflow
on:
  workflow_dispatch:
jobs:
  dump-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump/
        id: dump
        with:
          enable-context: "true"
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.ouuputs.dumped-date }}
