name: Environment
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: false
        description: Environment name
jobs:
  print-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name}}
    env:
      USERNAME: ${{ vars.USERNAME}}
      PASS: ${{secrets.PASS}}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASS:0:1} ${PASS$?}"
