name: JSON functions
on:
    workflow_dispatch:
jobs:
    json:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${CONTEXT}"
              env:
                CONTEXT: ${{ toJson(github)}}