name: Manual

on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: HELLO
                required: true
                description: A cheerful word
            log-level:
                type: choice
                options:
                    - info
                    - debug
                    - error

jobs:
    run-manual-id:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{inputs.greeting}} log-level ${{inputs.log-level}}"