name: Matrix
on:
  workflow_dispatch:
jobs:
  matrix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "${{ runner.os }}"
        shell: bash
