name: Multi Matrix
on:
  workflow_dispatch:
jobs:
  matrix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${{ runner.os }}" && node --version
