name: GitHub Output
on:
  workflow_dispatch:
jobs:
  share-job:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Helllo" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result}}
        run: echo "${RESULT}"
  env-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ENV_RESULT=Helllo ENV" >> "${GITHUB_ENV}"
      - run: echo "${ENV_RESULT}"
