name: Share Job Data
on:
  workflow_dispatch:
jobs:
  before-job:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.generate.outputs.result}}
  after-job:
    runs-on: ubuntu-latest
    needs: [before-job]
    steps:
      - env:
          RESULT: ${{ needs.before-job.outputs.result}}
        run: echo "${RESULT}"
